#!/bin/bash

################################################################################
# Setup Script - Make bash scripts executable and show quick reference
################################################################################

echo "=============================================================="
echo "  Setup: Monocular Depth Estimation Pipeline"
echo "=============================================================="
echo ""

# Make scripts executable
chmod +x train_eval_aif.sh
chmod +x train_eval_coded.sh
chmod +x compare_models.sh

echo " Made scripts executable"
echo ""
echo "=============================================================="
echo "  Quick Reference Guide"
echo "=============================================================="
echo ""
echo "Available Scripts:"
echo ""
echo "1. train_eval_aif.sh"
echo "   → Train and evaluate model on All-in-Focus (AiF/Pinhole) RGB images"
echo "   → Input: Regular RGB images from 'rgb/' directories"
echo "   → Training: NYUv2 + LivingRoom1"
echo "   → Testing: Corridor + DiningRoom"
echo ""
echo "2. train_eval_coded.sh"
echo "   → Train and evaluate model on Coded Aperture RGB images"
echo "   → Input: Coded images from 'Codedphasecam-27Linear/' directories"
echo "   → Training: NYUv2 + LivingRoom1"
echo "   → Testing: Corridor + DiningRoom"
echo ""
echo "3. compare_models.sh"
echo "   → Compare metrics from both models side-by-side"
echo "   → Shows Abs Rel, RMSE, MAE, δ<1.25 for both test datasets"
echo ""
echo "=============================================================="
echo "  Usage"
echo "=============================================================="
echo ""
echo "Run individually:"
echo "  ./train_eval_aif.sh      # Train AiF RGB model"
echo "  ./train_eval_coded.sh    # Train Coded RGB model"
echo "  ./compare_models.sh      # Compare results"
echo ""
echo "Or run both models sequentially:"
echo "  ./train_eval_aif.sh && ./train_eval_coded.sh && ./compare_models.sh"
echo ""
echo "=============================================================="
echo "  Dataset Structure Required"
echo "=============================================================="
echo ""
echo "datasets/"
echo "├── LivingRoom1/          # Training (Blender)"
echo "│   ├── rgb/              # Regular RGB images"
echo "│   ├── Codedphasecam-27Linear/  # Coded images"
echo "│   └── depth/            # Depth maps (.exr)"
echo "├── nyu_data/             # Training (NYU)"
echo "│   ├── rgb/"
echo "│   ├── Codedphasecam-27Linear/"
echo "│   └── depth/            # Depth maps (.png)"
echo "├── Corridor/             # Test (Blender)"
echo "│   ├── rgb/"
echo "│   ├── Codedphasecam-27Linear/"
echo "│   └── depth/"
echo "└── DiningRoom/           # Test (Blender)"
echo "    ├── rgb/"
echo "    ├── Codedphasecam-27Linear/"
echo "    └── depth/"
echo ""
echo "=============================================================="
echo "  Output Structure"
echo "=============================================================="
echo ""
echo "After running scripts, you'll have:"
echo ""
echo "checkpoints/"
echo "├── MetricWeightedLoss_RGB/      # AiF model checkpoints"
echo "│   ├── best.pt"
echo "│   ├── final.pt"
echo "│   └── epoch_*.pt"
echo "└── MetricWeightedLoss_CODED/    # Coded model checkpoints"
echo "    ├── best.pt"
echo "    ├── final.pt"
echo "    └── epoch_*.pt"
echo ""
echo "results_aif/                     # AiF predictions"
echo "├── Corridor/pred_depth/*.png"
echo "└── DiningRoom/pred_depth/*.png"
echo ""
echo "results_coded/                   # Coded predictions"
echo "├── Corridor/pred_depth/*.png"
echo "└── DiningRoom/pred_depth/*.png"
echo ""
echo "visualizations_aif/              # AiF visualizations"
echo "├── Corridor/"
echo "│   ├── comparison_*.png"
echo "│   └── metrics.txt"
echo "└── DiningRoom/"
echo "    ├── comparison_*.png"
echo "    └── metrics.txt"
echo ""
echo "visualizations_coded/            # Coded visualizations"
echo "├── Corridor/"
echo "│   ├── comparison_*.png"
echo "│   └── metrics.txt"
echo "└── DiningRoom/"
echo "    ├── comparison_*.png"
echo "    └── metrics.txt"
echo ""
echo "=============================================================="
echo "  Notes"
echo "=============================================================="
echo ""
echo "- Each script trains for 80 epochs (~several hours on GPU)"
echo "- Best model is saved based on L1 error < 3m"
echo "- Visualizations use viridis (AiF) and plasma (Coded) colormaps"
echo "- Metrics are saved in metrics.txt files"
echo "- To enable W&B logging, edit USE_WANDB=true in the scripts"
echo ""
echo "=============================================================="
echo "  Ready to go!"
echo "=============================================================="
echo ""
